name: Check and Test Package
on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main

# this cancels workflows currently in progress if you start a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-and-test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Install Roc
        uses: roc-lang/setup-roc@39c354a6a838a0089eea9068a0414f49b62c5c08
        with:
          version: alpha4-rolling
      - name: Roc check main.roc
        run: roc check package/main.roc
      - name: Roc test main.roc
        run: roc test package/main.roc